version: '3'

services:
  nginx:
    image: nginx
    ports:
      - "8088:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web1
      - web2

  web1:
    build:
      context: ./web1
      dockerfile: Dockerfile
   

  web2:
    build:
      context: ./web2
      dockerfile: Dockerfile
   
